# Python for AI — Session 2: Lab Notebook
### Duration: ~3 hours

This lab reinforces Session 2 topics through hands-on exercises.
Write your code in the empty cells provided.

**Topics:**
1. OOP essentials
2. NumPy array operations
3. Pandas data loading, cleaning, and analysis


## 1. OOP Essentials — Exercises (60 min)

**Task 1.1:** Create a class `Car` with attributes `brand`, `model`, `year` and a method `info()` that returns a formatted string describing the car.

**Task 1.2:** Create a class `ElectricCar` that inherits from `Car` and adds an attribute `battery_range`. Override `info()` to include battery range.

**Task 1.3 (AI-related):** Create a class `SimpleDataset` that:
- Takes a list of data in `__init__`
- Implements `__len__` to return the size of the dataset
- Implements `__getitem__` to return an item by index
- Has a method `add_sample(sample)` to append new data

Test your class by creating an instance, adding samples, checking its length, and accessing items by index.


In [1]:
# Task 1.1
class Car:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def info(self):
        return f"{self.brand} {self.model} ({self.year})"

car = Car("Porsche", "Cayenne", 2024)

print(car.info())


Porsche Cayenne (2024)


In [2]:
# Task 1.2
class Car:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def info(self):
        return f"{self.brand} {self.model} ({self.year})"


class ElectricCar(Car):
    def __init__(self, brand, model, year, battery_range):
        super().__init__(brand, model, year)
        self.battery_range = battery_range

    def info(self):
        return f"{self.brand} {self.model} ({self.year}) - Battery Range: {self.battery_range} km"

car = ElectricCar("Mercedes-Benz", "EQB", 2023, 260)

print(car.info())

Mercedes-Benz EQB (2023) - Battery Range: 260 km


In [3]:
# Task 1.3
class SimpleDataset:
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

    def add_sample(self, sample):
        self.data.append(sample)


dataset = SimpleDataset([10, 20, 30])

print("Length:", len(dataset))

print("Item at index 1:", dataset[1])

dataset.add_sample(40)

print("New Length:", len(dataset))

print("Item at index 3:", dataset[3])


Length: 3
Item at index 1: 20
New Length: 4
Item at index 3: 40


## 2. NumPy Array Operations — Exercises (60 min)

**Task 2.1:** Create a NumPy array of the numbers 1 to 20, reshape it into a (4, 5) matrix.

**Task 2.2:** From the matrix in 2.1, extract: the third row, the last column, and the sub-matrix of the first 2 rows and first 3 columns.

**Task 2.3:** Create two random arrays of shape (3, 3) using `np.random.rand`. Compute their element-wise sum, their matrix product (`np.dot` or `@`), and the transpose of the first array.

**Task 2.4:** Given `data = np.array([12, 45, 7, 23, 56, 89, 3])`, compute the mean, standard deviation, min, max, and sort the array in descending order.


In [4]:
# Task 2.1
import numpy as np

arr = np.arange(1, 21)

matrix = arr.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# Task 2.2
print("Third Row:")
print(matrix[2])

print("Last Column:")
print(matrix[:, -1])

print("Sub Matrix:")
print(matrix[:2, :3])


Third Row:
[11 12 13 14 15]
Last Column:
[ 5 10 15 20]
Sub Matrix:
[[1 2 3]
 [6 7 8]]


In [6]:
# Task 2.3
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)

print("Array A:")
print(a)

print("Array B:")
print(b)

print("Element-wise Sum:")
print(a + b)

print("Matrix Product:")
print(a @ b)

print("Transpose:")
print(a.T)

Array A:
[[0.85109978 0.00596789 0.41108559]
 [0.20032102 0.19217405 0.29535274]
 [0.87268559 0.92887193 0.19448468]]
Array B:
[[0.67398345 0.21364395 0.33197347]
 [0.76465764 0.48950018 0.06727949]
 [0.50334346 0.28551521 0.89348098]]
Element-wise Sum:
[[1.52508323 0.21961184 0.74305906]
 [0.96497866 0.68167423 0.36263224]
 [1.37602905 1.21438714 1.08796566]]
Matrix Product:
[[0.7851078  0.30212479 0.65024122]
 [0.43062428 0.22119431 0.34332269]
 [1.39633726 0.69665531 0.52597086]]
Transpose:
[[0.85109978 0.20032102 0.87268559]
 [0.00596789 0.19217405 0.92887193]
 [0.41108559 0.29535274 0.19448468]]


In [7]:
# Task 2.4
data = np.array([12, 45, 7, 23, 56, 89, 3])

print("Mean:", data.mean())
print("Std:", data.std())
print("Min:", data.min())
print("Max:", data.max())
print("Sorted:", np.sort(data)[::-1])


Mean: 33.57142857142857
Std: 29.090288722513286
Min: 3
Max: 89
Sorted: [89 56 45 23 12  7  3]


## 3. Pandas: Data Loading, Cleaning, and Analysis — Exercises (60 min)

Use this sample dataset for all tasks below:

```python
data = {
    "employee": ["Ali", "Sara", "Omar", "Mona", "Youssef", "Laila"],
    "department": ["IT", "HR", "IT", "Finance", "HR", None],
    "salary": [5000, 4500, None, 6000, 4800, 5200],
    "years_experience": [2, 5, 3, None, 4, 6]
}
```

**Task 3.1:** Load the dictionary above into a DataFrame `df`. Display `df.info()` and `df.describe()`.

**Task 3.2:** Handle missing values: fill missing `salary` and `years_experience` with the column mean, and fill missing `department` with `"Unknown"`.

**Task 3.3:** Filter and display only employees with more than 3 years of experience.

**Task 3.4:** Group the data by `department` and compute the average salary per department.

**Task 3.5 (Challenge):** Create a new column `senior` that is `True` if `years_experience >= 5`, else `False`. Then show the average salary grouped by `senior`.


In [8]:
# Task 3.1
import pandas as pd

data = {
    "employee": ["Ali", "Sara", "Omar", "Mona", "Youssef", "Laila"],
    "department": ["IT", "HR", "IT", "Finance", "HR", None],
    "salary": [5000, 4500, None, 6000, 4800, 5200],
    "years_experience": [2, 5, 3, None, 4, 6]
}

df = pd.DataFrame(data)

print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   employee          6 non-null      object 
 1   department        5 non-null      object 
 2   salary            5 non-null      float64
 3   years_experience  5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes
None
            salary  years_experience
count     5.000000          5.000000
mean   5100.000000          4.000000
std     565.685425          1.581139
min    4500.000000          2.000000
25%    4800.000000          3.000000
50%    5000.000000          4.000000
75%    5200.000000          5.000000
max    6000.000000          6.000000


In [9]:
# Task 3.2
df["salary"] = df["salary"].fillna(df["salary"].mean())

df["years_experience"] = df["years_experience"].fillna(
    df["years_experience"].mean()
)

df["department"] = df["department"].fillna("Unknown")

print(df)


  employee department  salary  years_experience
0      Ali         IT  5000.0               2.0
1     Sara         HR  4500.0               5.0
2     Omar         IT  5100.0               3.0
3     Mona    Finance  6000.0               4.0
4  Youssef         HR  4800.0               4.0
5    Laila    Unknown  5200.0               6.0


In [10]:
# Task 3.3
experienced = df[df["years_experience"] > 3]

print(experienced)


  employee department  salary  years_experience
1     Sara         HR  4500.0               5.0
3     Mona    Finance  6000.0               4.0
4  Youssef         HR  4800.0               4.0
5    Laila    Unknown  5200.0               6.0


In [11]:
# Task 3.4
average_salary = df.groupby("department")["salary"].mean()

print(average_salary)

department
Finance    6000.0
HR         4650.0
IT         5050.0
Unknown    5200.0
Name: salary, dtype: float64


In [12]:
# Task 3.5
df["senior"] = df["years_experience"] >= 5

average_salary = df.groupby("senior")["salary"].mean()

print(df)

print(average_salary)

  employee department  salary  years_experience  senior
0      Ali         IT  5000.0               2.0   False
1     Sara         HR  4500.0               5.0    True
2     Omar         IT  5100.0               3.0   False
3     Mona    Finance  6000.0               4.0   False
4  Youssef         HR  4800.0               4.0   False
5    Laila    Unknown  5200.0               6.0    True
senior
False    5225.0
True     4850.0
Name: salary, dtype: float64


## Wrap-up

Great job! You practiced OOP, NumPy, and Pandas — the exact building blocks used in real AI/ML pipelines.
